version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5
     steps:
       - checkout
       - run: echo "hello world"
            name: Testing YoutuAudioLink Class
            command: ./my_testing_script.sh
            shell: /bin/bash