version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5
     steps:
       - checkout
       - run: php --version
       - run: mkdir -p $CIRCLE_TEST_REPORTS/phpunit
       - run:
           name: Running Tests
           command: phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml tests

       