
machine:
 php:
   version: 5.6
build:
 steps:
   - checkout
   - run: php --version
   
dependencies:
  post:
    - wget https://phar.phpunit.de/phpunit-5.7.phar
    - chmod +x phpunit-5.7.phar
    - mv phpunit-5.7.phar phpunit

test:
 override:
   - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
   - phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml tests
