version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     override:
       - ~/phpunit
     steps:
       - checkout
       - run:
          shell: /bin/bash
          name: Running Tests
          command: |
            mkdir -p ~/phpunitD
            wget https://phar.phpunit.de/phpunit-5.7.phar
            chmod +x phpunit-5.7.phar
            mv phpunit-5.7.phar ~/phpunit
            ~/phpunit --log-junit ~/phpunitD/junit.xml tests
          when: always
       - store_test_results:
           path: ~/phpunit
       - store_artifacts:
           path: ~/phpunit 

workflows:
  version: 2
  build_and_test:
    jobs:
      - build