version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5
     steps:
       - checkout
       - run: php --version

   test:
    docker:
      - image: circleci/php:5
    steps:
      - checkout
      - run: mkdir -p ~/phpunitD
      - run: wget https://phar.phpunit.de/phpunit-5.7.phar
      - run: chmod +x phpunit-5.7.phar
      - run: mv phpunit-5.7.phar phpunit.phar
      - run:
          name: Running Tests
          command: phpunit --log-junit phpunitD/junit.xml tests
          background: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test