version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5
     steps:
       - checkout
       - run: php --version

       test:
        docker:
          - image: circleci/circleci/php:5
        steps:
          - checkout
          - run: mkdir -p ~/phpunit
          - run:
           name: Running Tests
           command: phpunit --log-junit phpunit/junit.xml tests
           background: true
       