version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5
     steps:
       - checkout
       run: echo "Test"
     test:
      override:
        - mkdir -p $CIRCLE_TEST_REPORTS/phpunit
        - phpunit --log-junit $CIRCLE_TEST_REPORTS/phpunit/junit.xml tests

       