version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5.6
     override:
       - ~/phpunit
     steps:
       - checkout
       - run: php --version
       - run:
          shell: /bin/bash
          command: |
            mkdir -p ~/phpunitD
            wget https://phar.phpunit.de/phpunit-5.7.phar
            chmod +x phpunit-5.7.phar
            mv phpunit-5.7.phar ~/phpunit
            phpunit --log-junit ~/phpunitD/junit.xml tests
          when: always
       - store_test_results:
           path: ~/phpunit
       - store_artifacts:
           path: ~/phpunit 

   test:
    docker:
      - image: circleci/php:5
    steps:
      - checkout
      - run: mkdir -p ~/phpunitD
      - run: wget https://phar.phpunit.de/phpunit-5.7.phar
      - run: chmod +x phpunit-5.7.phar
      - run: mv phpunit-5.7.phar usr/local/bin/phpunit
      - run:
          name: Running Tests
          command: phpunit --log-junit phpunitD/junit.xml tests
          background: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build