version: 2
jobs:
   build:
     docker:
       - image: circleci/php:5
     steps:
       - checkout
       - run:
            name: Testing application
            command: ./run_tests.sh
            shell: /bin/bash
